apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
