apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_USER: app
  DATABASE_NAME: app
  APP_PORT: "3000"
  NODE_ENV: development
  JWT_EXPIRES_IN: 1d
