apiVersion: v1
kind: Secret
metadata:
  name: autoflow-secrets
  namespace: autoflow
type: Opaque
stringData:
  NODE_ENV: production
  DB_HOST: fiap-tcdb-dev-postgres.cj6euquukf7c.us-east-1.rds.amazonaws.com
  DB_PORT: '5432'
  DB_USER: app
  DB_PASS: AutoFlow2024Strong
  DB_NAME: app
  JWT_SECRET: AutoFlowJwtSecret2024
  JWT_EXPIRES_IN: 1d
  NEW_RELIC_ENABLED: true
  NEW_RELIC_APP_NAME: autoflow-tc
  NEW_RELIC_LICENSE_KEY: ACA8F1220E819EA0FE79C5BC29E48C2A0945F7F56A23E03EBB99BDFAB6DDCF5B
  NEW_RELIC_LOG_LEVEL: info
