name: Prod
variables:
  - name: BASE_URL
    value: "{{KONG}}/api"
  - name: LAMBDA_URL
    value: "{{KONG}}/auth"
  - name: KONG
    value: aaae491f7594e4932ab643d4c30aaf4a-19db186db12929b4.elb.us-east-1.amazonaws.com
